DROP TABLE IF EXISTS `countries` ;

CREATE TABLE IF NOT EXISTS `countries` (
  `id` INT NOT NULL,
  `name_en` VARCHAR(45) NULL,
  `name_ru` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- INSERT INTO countries (id, name_en, name_ru) VALUES ...

INSERT INTO countries VALUES (805, 'Yemen', 'Йемен');
INSERT INTO countries VALUES (804, 'Panama', 'Панама');
INSERT INTO countries VALUES (801, 'Israel', 'Израиль');
INSERT INTO countries VALUES (800, 'Costa Rica', 'Коста-Рика');
INSERT INTO countries VALUES (709, 'Marshall Islands', 'Маршалловы Острова');
INSERT INTO countries VALUES (702, 'Federated States of Micronesia', 'Федеративные Штаты Микронезии');
INSERT INTO countries VALUES (419, 'Peru', 'Перу');
INSERT INTO countries VALUES (668, 'India', 'Индия');
INSERT INTO countries VALUES (1019, 'Madagascar', 'Мадагаскар');
INSERT INTO countries VALUES (664, 'New Zealand', 'Новая Зеландия');
INSERT INTO countries VALUES (414, 'Argentina', 'Аргентина');
INSERT INTO countries VALUES (142, 'France', 'Франция');
INSERT INTO countries VALUES (55, 'Netherlands', 'Нидерланды');
INSERT INTO countries VALUES (145, 'United Kingdom', 'Великобритания');
INSERT INTO countries VALUES (781, 'Antigua and Barbuda', 'Антигуа и Барбуда');
INSERT INTO countries VALUES (148, 'China', 'Китайская Народная Республика');
INSERT INTO countries VALUES (783, 'Honduras', 'Гондурас');
INSERT INTO countries VALUES (784, 'Dominica', 'Доминика');
INSERT INTO countries VALUES (786, 'Dominican Republic', 'Доминиканская Республика');
INSERT INTO countries VALUES (924, 'Tanzania', 'Танзания');
INSERT INTO countries VALUES (1011, 'Cape Verde', 'Кабо-Верде');
INSERT INTO countries VALUES (833, 'Malaysia', 'Малайзия');
INSERT INTO countries VALUES (711, 'Mongolia', 'Монголия');
INSERT INTO countries VALUES (710, 'Kiribati', 'Кирибати');
INSERT INTO countries VALUES (836, 'Myanmar', 'Мьянма');
INSERT INTO countries VALUES (837, 'Nepal', 'Непал');
INSERT INTO countries VALUES (183, 'Germany', 'Германия');
INSERT INTO countries VALUES (408, 'Australia', 'Австралия');
INSERT INTO countries VALUES (252, 'Indonesia', 'Индонезия');
INSERT INTO countries VALUES (399, 'Armenia', 'Армения');
INSERT INTO countries VALUES (398, 'Bahrain', 'Бахрейн');
INSERT INTO countries VALUES (403, 'Serbia', 'Сербия');
INSERT INTO countries VALUES (907112, 'Transnistria', 'Приднестровская Молдавская Республика');
INSERT INTO countries VALUES (657, 'Chad', 'Чад');
INSERT INTO countries VALUES (258, 'South Africa', 'Южно-Африканская Республика');
INSERT INTO countries VALUES (45, 'Portugal', 'Португалия');
INSERT INTO countries VALUES (159, 'Russia', 'Россия');
INSERT INTO countries VALUES (43, 'Turkey', 'Турция');
INSERT INTO countries VALUES (40, 'Austria', 'Австрия');
INSERT INTO countries VALUES (41, 'Greece', 'Греция');
INSERT INTO countries VALUES (155, 'Brazil', 'Бразилия');
INSERT INTO countries VALUES (792, 'El Salvador', 'Сальвадор');
INSERT INTO countries VALUES (790, 'Haiti', 'Республика Гаити');
INSERT INTO countries VALUES (796, 'Iraq', 'Ирак');
INSERT INTO countries VALUES (34754, 'Somaliland', 'Сомалиленд');
INSERT INTO countries VALUES (794, 'Iran', 'Иран');
INSERT INTO countries VALUES (954, 'Zimbabwe', 'Зимбабве');
INSERT INTO countries VALUES (889, 'Afghanistan', 'Афганистан');
INSERT INTO countries VALUES (884, 'South Korea', 'Республика Корея');
INSERT INTO countries VALUES (958, 'South Sudan', 'Южный Судан');
INSERT INTO countries VALUES (881, 'Vietnam', 'Вьетнам');
INSERT INTO countries VALUES (986, 'Eritrea', 'Эритрея');
INSERT INTO countries VALUES (826, 'Maldives', 'Мальдивы');
INSERT INTO countries VALUES (822, 'Lebanon', 'Ливан');
INSERT INTO countries VALUES (241, 'Cuba', 'Куба');
INSERT INTO countries VALUES (242, 'Belize', 'Белиз');
INSERT INTO countries VALUES (244, 'Barbados', 'Барбадос');
INSERT INTO countries VALUES (983, 'Equatorial Guinea', 'Экваториальная Гвинея');
INSERT INTO countries VALUES (23681, 'Northern Cyprus', 'Турецкая Республика Северного Кипра');
INSERT INTO countries VALUES (33, 'Finland', 'Финляндия');
INSERT INTO countries VALUES (32, 'Luxembourg', 'Люксембург');
INSERT INTO countries VALUES (31, 'Belgium', 'Бельгия');
INSERT INTO countries VALUES (30, 'United States', 'Соединённые Штаты Америки');
INSERT INTO countries VALUES (37, 'Lithuania', 'Литва');
INSERT INTO countries VALUES (36, 'Poland', 'Польша');
INSERT INTO countries VALUES (35, 'Denmark', 'Дания');
INSERT INTO countries VALUES (34, 'Sweden', 'Швеция');
INSERT INTO countries VALUES (928, 'Philippines', 'Филиппины');
INSERT INTO countries VALUES (929, 'Central African Republic', 'Центральноафриканская Республика');
INSERT INTO countries VALUES (39, 'Switzerland', 'Швейцария');
INSERT INTO countries VALUES (38, 'Italy', 'Италия');
INSERT INTO countries VALUES (858, 'Syria', 'Сирия');
INSERT INTO countries VALUES (423, 'North Korea', 'Корейская Народно-Демократическая Республика');
INSERT INTO countries VALUES (953, 'Zambia', 'Замбия');
INSERT INTO countries VALUES (851, 'Saudi Arabia', 'Саудовская Аравия');
INSERT INTO countries VALUES (733, 'Paraguay', 'Парагвай');
INSERT INTO countries VALUES (29999, 'Kingdom of the Netherlands', 'Королевство Нидерландов');
INSERT INTO countries VALUES (854, 'Sri Lanka', 'Шри-Ланка');
INSERT INTO countries VALUES (734, 'Guyana', 'Гайана');
INSERT INTO countries VALUES (819, 'Laos', 'Лаос');
INSERT INTO countries VALUES (40362, 'Sahrawi Arab Democratic Republic', 'Сахарская Арабская Демократическая Республика');
INSERT INTO countries VALUES (730, 'Suriname', 'Суринам');
INSERT INTO countries VALUES (1013, 'Lesotho', 'Лесото');
INSERT INTO countries VALUES (235, 'Monaco', 'Монако');
INSERT INTO countries VALUES (236, 'Montenegro', 'Черногория');
INSERT INTO countries VALUES (237, 'Vatican City', 'Ватикан');
INSERT INTO countries VALUES (230, 'Georgia (country)', 'Грузия');
INSERT INTO countries VALUES (232, 'Kazakhstan', 'Казахстан');
INSERT INTO countries VALUES (233, 'Malta', 'Мальта');
INSERT INTO countries VALUES (334, 'Singapore', 'Сингапур');
INSERT INTO countries VALUES (238, 'San Marino', 'Сан-Марино');
INSERT INTO countries VALUES (20, 'Norway', 'Норвегия');
INSERT INTO countries VALUES (1045, 'Somalia', 'Сомали');
INSERT INTO countries VALUES (1044, 'Sierra Leone', 'Сьерра-Леоне');
INSERT INTO countries VALUES (1042, 'Seychelles', 'Сейшельские Острова');
INSERT INTO countries VALUES (1041, 'Senegal', 'Сенегал');
INSERT INTO countries VALUES (27, 'Republic of Ireland', 'Ирландия');
INSERT INTO countries VALUES (28, 'Hungary', 'Венгрия');
INSERT INTO countries VALUES (29, 'Spain', 'Испания');
INSERT INTO countries VALUES (1049, 'Sudan', 'Судан');
INSERT INTO countries VALUES (1025, 'Mauritania', 'Мавритания');
INSERT INTO countries VALUES (1027, 'Mauritius', 'Маврикий');
INSERT INTO countries VALUES (1020, 'Malawi', 'Малави');
INSERT INTO countries VALUES (189, 'Iceland', 'Исландия');
INSERT INTO countries VALUES (843, 'Pakistan', 'Пакистан');
INSERT INTO countries VALUES (842, 'Oman', 'Оман');
INSERT INTO countries VALUES (184, 'Belarus', 'Белоруссия');
INSERT INTO countries VALUES (1029, 'Mozambique', 'Мозамбик');
INSERT INTO countries VALUES (846, 'Qatar', 'Катар');
INSERT INTO countries VALUES (736, 'Ecuador', 'Эквадор');
INSERT INTO countries VALUES (265, 'Uzbekistan', 'Узбекистан');
INSERT INTO countries VALUES (347, 'Liechtenstein', 'Лихтенштейн');
INSERT INTO countries VALUES (227, 'Azerbaijan', 'Азербайджан');
INSERT INTO countries VALUES (225, 'Bosnia and Herzegovina', 'Босния и Герцеговина');
INSERT INTO countries VALUES (224, 'Croatia', 'Хорватия');
INSERT INTO countries VALUES (222, 'Albania', 'Албания');
INSERT INTO countries VALUES (221, 'Republic of Macedonia', 'Республика Македония');
INSERT INTO countries VALUES (96, 'Mexico', 'Мексика');
INSERT INTO countries VALUES (229, 'Cyprus', 'Республика Кипр');
INSERT INTO countries VALUES (228, 'Andorra', 'Андорра');
INSERT INTO countries VALUES (1050, 'Swaziland', 'Свазиленд');
INSERT INTO countries VALUES (17, 'Japan', 'Япония');
INSERT INTO countries VALUES (16, 'Canada', 'Канада');
INSERT INTO countries VALUES (424, 'Cambodia', 'Камбоджа');
INSERT INTO countries VALUES (1028, 'Morocco', 'Марокко');
INSERT INTO countries VALUES (902, 'Bangladesh', 'Бангладеш');
INSERT INTO countries VALUES (25230, 'Bailiwick of Guernsey', 'Гернси');
INSERT INTO countries VALUES (1036, 'Uganda', 'Уганда');
INSERT INTO countries VALUES (1037, 'Rwanda', 'Руанда');
INSERT INTO countries VALUES (1008, 'Ivory Coast', 'Кот-д’Ивуар');
INSERT INTO countries VALUES (1032, 'Niger', 'Нигер');
INSERT INTO countries VALUES (262, 'Algeria', 'Алжир');
INSERT INTO countries VALUES (1030, 'Namibia', 'Намибия');
INSERT INTO countries VALUES (191, 'Estonia', 'Эстония');
INSERT INTO countries VALUES (965, 'Burkina Faso', 'Буркина-Фасо');
INSERT INTO countries VALUES (717, 'Venezuela', 'Венесуэла');
INSERT INTO countries VALUES (967, 'Burundi', 'Бурунди');
INSERT INTO countries VALUES (962, 'Benin', 'Бенин');
INSERT INTO countries VALUES (963, 'Botswana', 'Ботсвана');
INSERT INTO countries VALUES (697, 'Nauru', 'Науру');
INSERT INTO countries VALUES (298, 'Chile', 'Чили');
INSERT INTO countries VALUES (695, 'Palau', 'Палау');
INSERT INTO countries VALUES (115, 'Ethiopia', 'Эфиопия');
INSERT INTO countries VALUES (114, 'Kenya', 'Кения');
INSERT INTO countries VALUES (117, 'Ghana', 'Гана');
INSERT INTO countries VALUES (691, 'Papua New Guinea', 'Папуа — Новая Гвинея');
INSERT INTO countries VALUES (757, 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины');
INSERT INTO countries VALUES (754, 'Trinidad and Tobago', 'Тринидад и Тобаго');
INSERT INTO countries VALUES (750, 'Bolivia', 'Боливия');
INSERT INTO countries VALUES (212, 'Ukraine', 'Украина');
INSERT INTO countries VALUES (213, 'Czech Republic', 'Чехия');
INSERT INTO countries VALUES (211, 'Latvia', 'Латвия');
INSERT INTO countries VALUES (217, 'Moldova', 'Молдавия');
INSERT INTO countries VALUES (214, 'Slovakia', 'Словакия');
INSERT INTO countries VALUES (215, 'Slovenia', 'Словения');
INSERT INTO countries VALUES (218, 'Romania', 'Румыния');
INSERT INTO countries VALUES (219, 'Bulgaria', 'Болгария');
INSERT INTO countries VALUES (912, 'Mali', 'Мали');
INSERT INTO countries VALUES (917, 'Bhutan', 'Бутан');
INSERT INTO countries VALUES (916, 'Angola', 'Ангола');
INSERT INTO countries VALUES (1000, 'Gabon', 'Габон');
INSERT INTO countries VALUES (1007, 'Guinea-Bissau', 'Гвинея-Бисау');
INSERT INTO countries VALUES (1006, 'Guinea', 'Гвинея');
INSERT INTO countries VALUES (1005, 'The Gambia', 'Гамбия');
INSERT INTO countries VALUES (712, 'Fiji', 'Фиджи');
INSERT INTO countries VALUES (977, 'Djibouti', 'Джибути');
INSERT INTO countries VALUES (1009, 'Cameroon', 'Камерун');
INSERT INTO countries VALUES (974, 'Democratic Republic of the Congo', 'Демократическая Республика Конго');
INSERT INTO countries VALUES (971, 'Republic of the Congo', 'Республика Конго');
INSERT INTO countries VALUES (970, 'Comoros', 'Коморы');
INSERT INTO countries VALUES (683, 'Samoa', 'Самоа');
INSERT INTO countries VALUES (769, 'Grenada', 'Гренада');
INSERT INTO countries VALUES (685, 'Solomon Islands', 'Соломоновы Острова');
INSERT INTO countries VALUES (686, 'Vanuatu', 'Вануату');
INSERT INTO countries VALUES (763, 'Saint Kitts and Nevis', 'Сент-Китс и Невис');
INSERT INTO countries VALUES (760, 'Saint Lucia', 'Сент-Люсия');
INSERT INTO countries VALUES (766, 'Jamaica', 'Ямайка');
INSERT INTO countries VALUES (9676, 'Isle of Man', 'Остров Мэн');
INSERT INTO countries VALUES (1033, 'Nigeria', 'Нигерия');
INSERT INTO countries VALUES (874, 'Turkmenistan', 'Туркмения');
INSERT INTO countries VALUES (6250, 'Western Sahara', 'Западная Сахара');
INSERT INTO countries VALUES (219060, 'State of Palestine', 'Государство Палестина');
INSERT INTO countries VALUES (79, 'Egypt', 'Египет');
INSERT INTO countries VALUES (77, 'Uruguay', 'Уругвай');
INSERT INTO countries VALUES (574, 'East Timor', 'Восточный Тимор');
INSERT INTO countries VALUES (878, 'United Arab Emirates', 'Объединённые Арабские Эмираты');
INSERT INTO countries VALUES (774, 'Guatemala', 'Гватемала');
INSERT INTO countries VALUES (948, 'Tunisia', 'Тунис');
INSERT INTO countries VALUES (817, 'Kuwait', 'Кувейт');
INSERT INTO countries VALUES (810, 'Jordan', 'Иордания');
INSERT INTO countries VALUES (811, 'Nicaragua', 'Никарагуа');
INSERT INTO countries VALUES (813, 'Kyrgyzstan', 'Киргизия');
INSERT INTO countries VALUES (1014, 'Liberia', 'Либерия');
INSERT INTO countries VALUES (1016, 'Libya', 'Ливия');
INSERT INTO countries VALUES (1246, 'Kosovo', 'Республика Косово');
INSERT INTO countries VALUES (739, 'Colombia', 'Колумбия');
INSERT INTO countries VALUES (778, 'The Bahamas', 'Багамские Острова');
INSERT INTO countries VALUES (945, 'Togo', 'Того');
INSERT INTO countries VALUES (678, 'Tonga', 'Тонга');
INSERT INTO countries VALUES (1039, 'São Tomé and Príncipe', 'Сан-Томе и Принсипи');
INSERT INTO countries VALUES (672, 'Tuvalu', 'Тувалу');
INSERT INTO countries VALUES (921, 'Brunei', 'Бруней');
INSERT INTO countries VALUES (863, 'Tajikistan', 'Таджикистан');
INSERT INTO countries VALUES (865, 'Taiwan', 'Китайская Республика');
INSERT INTO countries VALUES (869, 'Thailand', 'Таиланд');
