INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2240, 159, 'Novgorod Oblast', 'Новгородская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5334, 159, 'Saratov Oblast', 'Саратовская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2246, 159, 'Nizhny Novgorod Oblast', 'Нижегородская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (1697, 159, 'Moscow Oblast', 'Московская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3550, 159, 'Tambov Oblast', 'Тамбовская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (7971, 159, 'Magadan Oblast', 'Магаданская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5338, 159, 'Orenburg Oblast', 'Оренбургская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (1759, 159, 'Murmansk Oblast', 'Мурманская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5219, 159, 'Ingushetia', 'Ингушетия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2164, 159, 'Nenets Autonomous Okrug', 'Ненецкий автономный округ');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5545, 159, 'Penza Oblast', 'Пензенская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5851, 159, 'Novosibirsk Oblast', 'Новосибирская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5835, 159, 'Omsk Oblast', 'Омская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5328, 159, 'Karachay-Cherkessia', 'Карачаево-Черкесия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5710, 159, 'Bashkortostan', 'Башкортостан');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2347, 159, 'Smolensk Oblast', 'Смоленская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (7730, 159, 'Jewish Autonomous Oblast', 'Еврейская автономная область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5340, 159, 'Mordovia', 'Мордовия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5387, 159, 'Kirov Oblast', 'Кировская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6886, 159, 'Amur Oblast', 'Амурская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5741, 159, 'Kurgan Oblast', 'Курганская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (4341, 159, 'Primorsky Krai', 'Приморский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6076, 159, 'Kemerovo Oblast', 'Кемеровская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5942, 159, 'Altai Krai', 'Алтайский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3573, 159, 'Rostov Oblast', 'Ростовская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3953, 159, 'Kalmykia', 'Калмыкия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6320, 159, 'Khanty-Mansi Autonomous Okrug', 'Ханты-Мансийский автономный округ — Югра');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5634, 159, 'Ulyanovsk Oblast', 'Ульяновская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5267, 159, 'Kabardino-Balkaria', 'Кабардино-Балкария');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6585, 159, 'Irkutsk Oblast', 'Иркутская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3734, 159, 'Adygea', 'Адыгея');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2810, 159, 'Bryansk Oblast', 'Брянская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (1749, 159, 'Kaliningrad Oblast', 'Калининградская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6543, 159, 'Khakassia', 'Хакасия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2191, 159, 'Leningrad Oblast', 'Ленинградская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6838, 159, 'Zabaykalsky Krai', 'Забайкальский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2073, 159, 'Komi Republic', 'Республика Коми');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3329, 159, 'Belgorod Oblast', 'Белгородская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6563, 159, 'Krasnoyarsk Krai', 'Красноярский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (15966495, 159, 'Republic of Crimea', 'Республика Крым');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5187, 159, 'Chechnya', 'Чечня');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5207, 159, 'Stavropol Krai', 'Ставропольский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5237, 159, 'North Ossetia-Alania', 'Северная Осетия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (7984, 159, 'Chukotka Autonomous Okrug', 'Чукотский автономный округ');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (7948, 159, 'Kamchatka Krai', 'Камчатский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6605, 159, 'Sakha Republic', 'Якутия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2015, 159, 'Vologda Oblast', 'Вологодская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2292, 159, 'Tver Oblast', 'Тверская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3447, 159, 'Voronezh Oblast', 'Воронежская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3819, 159, 'Volgograd Oblast', 'Волгоградская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (960, 159, 'Tuva', 'Тыва');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2753, 159, 'Ryazan Oblast', 'Рязанская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2448, 159, 'Yaroslavl Oblast', 'Ярославская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2654, 159, 'Ivanovo Oblast', 'Ивановская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (1727, 159, 'Samara Oblast', 'Самарская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5884, 159, 'Tomsk Oblast', 'Томская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (1914, 159, 'Republic of Karelia', 'Республика Карелия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5971, 159, 'Altai Republic', 'Республика Алтай');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (1875, 159, 'Arkhangelsk Oblast', 'Архангельская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2792, 159, 'Tula Oblast', 'Тульская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2218, 159, 'Pskov Oblast', 'Псковская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6809, 159, 'Buryatia', 'Бурятия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3129, 159, 'Oryol Oblast', 'Орловская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5446, 159, 'Mari El', 'Марий Эл');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2596, 159, 'Kostroma Oblast', 'Костромская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5462, 159, 'Sverdlovsk Oblast', 'Свердловская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (7788, 159, 'Khabarovsk Krai', 'Хабаровский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3178, 159, 'Kursk Oblast', 'Курская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3941, 159, 'Astrakhan Oblast', 'Астраханская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5481, 159, 'Tatarstan', 'Татарстан');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5714, 159, 'Chelyabinsk Oblast', 'Челябинская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5466, 159, 'Chuvashia', 'Чувашия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5400, 159, 'Perm Krai', 'Пермский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (6407, 159, 'Yamalo-Nenets Autonomous Okrug', 'Ямало-Ненецкий автономный округ');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2702, 159, 'Vladimir Oblast', 'Владимирская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5118, 159, 'Dagestan', 'Дагестан');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5824, 159, 'Tyumen Oblast', 'Тюменская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (5422, 159, 'Udmurtia', 'Удмуртия');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (2842, 159, 'Kaluga Oblast', 'Калужская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3680, 159, 'Krasnodar Krai', 'Краснодарский край');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (7797, 159, 'Sakhalin Oblast', 'Сахалинская область');
INSERT INTO regions (id, country_id, name_en, name_ru) VALUES (3510, 159, 'Lipetsk Oblast', 'Липецкая область');
