#added 2016-10
#List of `instances of` "programming language" only with a label.
SELECT ?item ?item_label
WHERE
{
	?item wdt:P31 wd:Q9143
    ; rdfs:label ?item_label . 
  
    FILTER (LANG(?item_label) = "en") . 
}

# https://query.wikidata.org/#%23added%202016-10%0A%23List%20of%20%60instances%20of%60%20%22programming%20language%22%20only%20with%20a%20label.%0ASELECT%20%3Fitem%20%3Fitem_label%0AWHERE%0A%7B%0A%09%3Fitem%20wdt%3AP31%20wd%3AQ9143%0A%20%20%20%20%3B%20rdfs%3Alabel%20%3Fitem_label%20.%20%0A%20%20%0A%20%20%20%20FILTER%20%28LANG%28%3Fitem_label%29%20%3D%20%22en%22%29%20.%20%0A%7D
# 710 Results in 362 ms  
